### ISSUE TITLE
Add font Inter as base64 SVG

### ISSUE THREAD

**Issue by tekkac** [Carbonable/metadata#62]
**Description**
---
Implement a Metadata component in [/src/components/component/fonts](../blob/main/src/components/component) that returns a base64 encoded version of the [Inter font](https://fonts.google.com/specimen/Inter).

Additional Information
---------------------------
[Easy - Cairo - Low Priority]

**Acceptance Criteria**
---

- [ ] Add the Inter font Metadata component.
- [ ] Implement and pass unit tests (e.g. tests from [here](../blob/main/src/components/component/sdgs/sdg01.cairo#L176))

**Comment by AryanGodara** [comment]
@tekkac @Khyati729 I'd really like to work on this issue :)
Will try to get this done on Monday. Could you please assign this to me

**Comment by Oshioke-Salaki** [comment]
Please can I get this done?

**Comment by Khyati729** [comment]
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue
